# The URL the site will be built for
base_url = "https://antonangeletti.com"
theme = "particle-zola"
description = "yap yap yap"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
username = "Anton Angeletti"
user_intro = "hey, i'm anton"
user_title = "i do computers"
email = "angelettianton@gmail.com"
github_username = "anton-3"
linkedin_username = "anton-angeletti"
user_description = "I'm a student at University of Nebraska-Lincoln, double majoring in Computer Science and Mathematics with a minor in Music. My interests include cybersecurity, software development, and networking, and I have experience in building full-stack web applications. In my free time, I like to go to hackathons, compete in <a target='_blank' href='https://en.wikipedia.org/wiki/Capture_the_flag_(cybersecurity)'>CTFs</a>, and play piano. I'm also pretty good at <a target='_blank' href='https://www.worldcubeassociation.org/persons/2024ANGE07'>solving Rubik's cubes</a>. Scroll down to see my portfolio!"
frontend_description = "On the frontend, I have experience in HTML, JavaScript, and React. In the projects I've worked on, my goal is always to build responsive and dynamic web applications with a focus on user experience and performance."
backend_description = "For backend development, the technologies I'm most skilled in are Node.js, Java, and Python, among others. In my current internship, most of my work is in developing Spring Boot applications in Java and Groovy."
tools_description = "I have experience with several software engineering tools, including Git/GitHub, Linux, the IntelliJ IDE, and others. I've used Git and GitHub in quite a few personal projects over the years, and I run Arch Linux on my personal laptop."

# TODO: replace the images with images of the projects, the hackathon pics are just a placeholder for now
project1_title = "lucky liars"
project1_description = "Lucky Liars is an AI-powered murder mystery game written in Rust, with a Node.js API and an integrated hardware display. It uses LLMs for character dialogue in-game, creating a unique experience every playthrough. I built it on a team of 4 at <a target='_blank' href='https://unlcornhacks.com/#/home'>CornHacks</a> 2024, and we ended up winning 1st place."
project1_link = "https://github.com/bald-rs/lucky-liars"
project1_img = "/img/cornhacks.jpg"

project2_title = "eduwiz"
project2_description = "EduWiz is another hackathon project of mine; it's a web app for promoting educational outcomes with gamified quizzes. My team developed it at <a target='_blank' href='https://hackkstate.tech/'>Hack K-State</a> 2023, and we won the prizes for Best Education Hack and Best Use of the Flow Cryptocurrency."
project2_link = "https://github.com/bald-rs/eduwiz"
project2_img = "/img/hackk-state.webp"

project3_title = "lexi"
project3_description = "Lexi is the project I built at my first ever hackathon, <a target='_blank' href='https://hackmidwest.com/'>Hack Midwest</a> 2023. It's a language learning app that integrates the OpenAI, Stable Diffusion, DeepL, and Pinata APIs to generate customized storybooks with pictures. We won a $2,500 prize for best use of the Pinata API for Web3 file storage."
project3_link = "https://github.com/anton-3/lexi"
project3_img = "/img/hackmidwest.webp"
